import { Noto_Sans_SC, Space_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/NavBar";

const notoSansSC = Noto_Sans_SC({
    variable: "--font-noto-sans-sc",
    subsets: ["chinese-simplified"],
    weight: ["300", "400", "500", "700", "900"],
    display: "swap",
});

const spaceMono = Space_Mono({
    variable: "--font-space-mono",
    subsets: ["latin"],
    weight: ["400", "700"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="zh-CN" className="scroll-smooth">
            <body
                className={`${notoSansSC.variable} ${spaceMono.variable} antialiased`}
            >
                <Navbar />
                <main>{children}</main>
            </body>
        </html>
    );
}
